### ISSUE TITLE
The output quality is severely degraded compared to the original llama.cpp

### ISSUE THREAD

**Issue by snowyu** [withcatai/node-llama-cpp#445]
### Issue description

In the following example, an empty list is always returned(LlamaCompletion). test on qwen2.5-7b-instruct.Q4_0, qwen2.5-3b-instruct.Q4_0, qwen2.5-1.5b-instruct.Q4_0

### Expected Behavior

should correctly return the list of languages:

```json
[
  {
    "name": "English",
    "value": "en"
  },
  {
    "name": "Spanish",
    "value": "es"
  },
  {
    "name": "French",
    "value": "fr"
  },
  {
    "name": "German",
    "value": "de"
  },
  {
    "name": "Italian",
    "value": "it"
  },
  {
    "name": "Portuguese",
    "value": "pt"
  },
  {
    "name": "Chinese (Simplified)",
    "value": "zh-Hans"
  },
  {
    "name": "Chinese (Traditional)",
    "value": "zh-Hant"
  },
  {
    "name": "Japanese",
    "value": "ja"
  },
  {
    "name": "Korean",
    "value": "ko"
  },
  {
    "name": "Russian",
    "value": "ru"
  },
  {
    "name": "Arabic",
    "value": "ar"
  },
  {
    "name": "Dutch",
    "value": "nl"
  },
  {
    "name": "Swedish",
    "value": "sv"
  },
  {
    "name": "Danish",
    "value": "da"
  },
  {
    "name": "Norwegian",
    "value": "no"
  },
  {
    "name": "Greek",
    "value": "el"
  },
  {
    "name": "Turkish",
    "value": "tr"
  },
  {
    "name": "Hebrew",
    "value": "he"
  },
  {
    "name": "Indonesian",
    "value": "id"
  },
  {
    "name": "Malay",
    "value": "ms"
  },
  {
    "name": "Thai",
    "value": "th"
  },
  {
    "name": "Vietnamese",
    "value": "vi"
  },
  {
    "name": "Hindi",
    "value": "hi"
  },
  {
    "name": "Urdu",
    "value": "ur"
  },
  {
    "name": "Tamil",
    "value": "ta"
  },
  {
    "name": "Gujarati",
    "value": "gu"
  },
  {
    "name": "Bengali",
    "value": "bn"
  },
  {
    "name": "Malayalam",
    "value": "ml"
  },
  {
    "name": "Tagalog",
    "value": "tl"
  }
]
```

All are ok when running on the original llama.cpp.

### Actual Behavior

```json
[]
```

I suspect it's a problem with the sampler.

### Steps to reproduce

parameters:

* "temperature":0
* "top_p":0.9
* "grammar":"char ::= [^\"\\\\\\x7F\\x00-\\x1F] | [\\\\] ([\"\\\\bfnrt] | \"u\" [0-9a-fA-F]{4})\nitem ::= \"{\" space  (item-name-kv item-name-rest | item-value-kv )? \"}\" space\nitem-name-kv ::= \"\\\"name\\\"\" space \":\" space string\nitem-name-rest ::= ( \",\" space item-value-kv )?\nitem-value-kv ::= \"\\\"value\\\"\" space \":\" space string\nroot ::= \"[\" space (item (\",\" space item)*)? \"]\" space\nspace ::= | \" \" | \"\\n\"{1,2} [ \\t]{0,20}\nstring ::= \"\\\"\" char* \"\\\"\" space\n"

The prompt:

```yaml
system: Accurately Extract THE INPUT CONTENT by the user as a JSON object according to THE JSON FIELDS in json schema format
  specified by the user:
  
user: THE JSON FIELDS IN JSON SCHEMA FORMAT:
  * (array)
  * name: (optional) (string) The language name
  * value: (optional) (string) The ISO 639-1 language code
  ---
  
  THE INPUT CONTENT:
  here are the language list:
  - English
  - Spanish
  - French
  - German
  - Italian
  - Portuguese
  - Chinese (Simplified and Traditional)
  - Japanese
  - Korean
  - Russian
  - Arabic
  - Dutch
  - Swedish
  - Danish
  - Norwegian
  - Greek
  - Turkish
  - Hebrew
  - Indonesian
  - Malay
  - Thai
  - Vietnamese
  - Hindi
  - Urdu
  - Tamil
  - Gujarati
  - Bengali
  - Malayalam
  - Tagalog
  ---
```

The Completion prompt:"<|im_start|>system\nAccurately Extract THE INPUT CONTENT by the user as a JSON object according to THE JSON FIELDS in json schema format specified by the user:<|im_end|>\n<|im_start|>user\n\nTHE JSON FIELDS IN JSON SCHEMA FORMAT:\n* (array)\n  * name: (optional) (string) The language name\n  * value: (optional) (string) The ISO 639-1 language code\n---\n\nTHE INPUT CONTENT:\nhere are the language list:\n- English\n- Spanish\n- French\n- German\n- Italian\n- Portuguese\n- Chinese (Simplified and Traditional)\n- Japanese\n- Korean\n- Russian\n- Arabic\n- Dutch\n- Swedish\n- Danish\n- Norwegian\n- Greek\n- Turkish\n- Hebrew\n- Indonesian\n- Malay\n- Thai\n- Vietnamese\n- Hindi\n- Urdu\n- Tamil\n- Gujarati\n- Bengali\n- Malayalam\n- Tagalog\n---<|im_end|>\n<|im_start|>assistant\n"

run the original llama.cpp to compare: 

```bash
./llama-server -t 4 -c 8192 -ngl 66  -m ~/.local/share/ai/brain/qwen2.5-7b-instruct.Q4_0.gguf 
```

### My Environment

| Dependency               | Version             |
| ---                      | ---                 |
| Operating System         |                     |
| CPU                      | Intel i9 / Apple M1 |
| Node.js version          | x.y.zzz             |
| Typescript version       | x.y.zzz             |
| `node-llama-cpp` version | x.y.zzz             |

`npx --yes node-llama-cpp inspect gpu` output:
```
OS: Ubuntu 22.04.5 LTS (x64)
Node: 20.18.0 (x64)
TypeScript: 5.7.3
node-llama-cpp: 0.1.0

CUDA: available
Vulkan: Vulkan is detected, but using it failed
To resolve errors related to Vulkan, see the Vulkan guide: https://node-llama-cpp.withcat.ai/guide/vulkan

CPU model: AMD Ryzen 9 5900X 12-Core Processor
Math cores: 12
Used RAM: 11.96% (15.04GB/125.7GB)
Free RAM: 88.03% (110.66GB/125.7GB)
Used swap: 0% (0B/64GB)
Max swap size: 64GB
mmap: supported

```

### Relevant Features Used

- [ ] Metal support
- [ ] CUDA support
- [ ] Vulkan support
- [ ] Grammar
- [ ] Function calling

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.
